#!/usr/bin/env bash

# This function gets overwritten when sourced
profile::start() {
    if [[ "${FUNCNAME[1]-}" != "source" ]]; then
        echo "This file must be sourced for profiling to work."
        return 1
    fi
}

profile::start || exit 1
. "${BASH_SOURCE[0]%/*}/libprofile"
profile::start "$@"
